version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    depends_on:
      - rabbitmq_container
    command: python3 app.py
    environment:
      - RABBIT_HOST=rabbitmq_container
  rabbitmq_container:
    image: "rabbitmq:3.8.9-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq_container
  celery_worker:
    build: .
    command: celery -A celery_working worker --loglevel=info --pool=solo
    environment:
      - RABBIT_HOST=rabbitmq_container
